FROM golang:1.22.0

WORKDIR /app

COPY . .

RUN go build -o vecin ./cmd/webapp

ADD https://raw.githubusercontent.com/vishnubob/wait-for-it/master/wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

CMD /wait-for-it.sh vecin:5432 --timeout=45 -- ./vecin
